name: example
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flick_video_player:
    path: ../
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  video_player: ^0.11.1+2
  visibility_detector: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/iceland_poster.jpg
    - images/9th_may_poster.jpg
    - images/rio_from_above_poster.jpg
    - images/the_valley_poster.jpg
